### ISSUE TITLE
institution_id registration of HCLIMcom-DMI

### ISSUE THREAD

**Issue by obchristensen** [WCRP-CORDEX/cordex-cmip6-cv#120]
### institution_id

HCLIMcom-DMI

### institution

HARMONIE Climate Modelling Community (HCLIMcom) partner: Danish Meteorological Institute (DMI), Copenhagen, Denmark

**Comment by gnikulin** [comment]
@obchristensen  it should be `HARMONIE Climate Modelling Community (HCLIMcom) partner: Danish Meteorological lnstitute, Copenhagen, Denmark` so I updated `institution`

**Comment by jesusff** [comment]
/register

OK, looks good.

@obchristensen, @Ruth-Mottram, there are [simulations registered for DMI standalone](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=dmi) (no HCLIMcom), but the simulations are also with HCLIM43-ALADIN. Should we switch them to HCLIMcom-DMI? These are for polar regions (ANT-12), is the model configuration/components for ANT-12 exactly the same as for e.g. EURO-CORDEX? Otherwise, a different `source_id` should be registered.

**Comment by larsbuntemeyer** [comment]
I think there got an `l` mixed up with an `I` (hard to distinguish) un `Institute`. I'll fix it.

**Comment by gnikulin** [comment]
Seems we missed "(DMI)" after "Danish Meteorological Institute" should be: 

HARMONIE Climate Modelling Community (HCLIMcom) partner: Danish Meteorological Institute (DMI), Copenhagen, Denmark

**Comment by larsbuntemeyer** [comment]
/register

updating with missing `(DMI)`
