### ISSUE TITLE
source_id registration of ICTP RegCM model

### ISSUE THREAD

**Issue by graziano-giuliani** [WCRP-CORDEX/cordex-cmip6-cv#141]
### label

RegCM V5 MOLOCH

### label_extended

The ICTP RegCM version 5 using non hydrostatic MOLOCH dynamical core

### source_id

RegCM5-0

### source_type

ARCM

### release_year

2023

### activity_participation

DD

### institution_id

ICTP

### further_info_url

https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2022JD038199

### What license do you choose?

CC BY 4.0

**Comment by jesusff** [comment]
Hi @graziano-giuliani 

just to make sure that you will switch the model name (source_id) to all capitals (REGCM5-0) in the filenames and DRS in general for CORDEX-CMIP6. Is this coordinated across the RegCM community? I ask because there are plans to run previous versions of the model which, for the moment, use the RegCM mixed-case syntax, although they have not tried to register the model name yet.

https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=regcm

Please, could you also check the driving GCMs/scenarios and update their expected date for completion?
https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=ictp
(we'll change the RCM name in this list to REGCM5-0 for ICTP, if you confirm the above)

**Comment by graziano-giuliani** [comment]
Hi Jesus. Indeed the code would be RegCM5-0, but the capitalization went without my intervention. Does the form allow for mixed case? Or is it a problem generated by my Firefox client? For the simulations, we have as of now, as mentioned in the FPSCONV meeting, some issues with the HPC platform. We hope the problems to be solved during the summer. I would thus leave the expected dates as they are, hoping for the best, and update if needed only if we have bad news from the HPC provider. Some of the simulations will be run at ORNL and HKU, and indeed we are cross waiting, us for credentials, them for the model configuration which will be run on their cluster resources. The plan is unchanged, but we cannot currently put a figure on the (now probable) delay: all simulations (except Africa) have officially started the evaluation period, but are all now on hold with only a handful of simulated years until the HPC technical issues are closed.

**Comment by jesusff** [comment]
OK, thank you. Not sure what happened with the source_id capitalization. In principle, the template should not modify the entries. Anyway, I updated your original post to show the mixed-case version.
And thank you also for the update on your plans. I will just put some date in the future, to avoid having past expected dates. Good luck with the new HPC!
