### ISSUE TITLE
institution_id registration of CLMcom-IMWM

### ISSUE THREAD

**Issue by ajaczewski** [WCRP-CORDEX/cordex-cmip6-cv#183]
### institution_id

CLMcom-IMWM

### institution

Climate Limited-area Modelling Community (CLMcom) partner: Institute of Meteorology and Water Management, Warsaw, Poland

**Comment by jesusff** [comment]
Thank you, Adam. Is this for the CLMcom runs? the rest of the partners are showing this partnership explicitly in their `institution_id` (#144). You might need to register twice. Rather than registering institutions, we are registering here a controlled vocabulary for all `institution_id`s that will ultimately be allowed by ESGF into file and directory names. Thus, you might need to register both IMWM (e.g. for WRF runs) and CLMcom-IMWM (for ICON / COSMO CLM runs). We can use this issue for one of them but, please, clarify your plans (there's currently a mismatch between the title and the contents of this issue -- no problem in updating any of them)

**Comment by ajaczewski** [comment]
Hi Chus. Yes, this is for CLMcom. I have realised that it should be:

"Climate Limited-area Modelling Community (CLMcom) partner: Institute of Meteorology and Water Management, Warsaw, Poland"

I have followed CLMcom's rule, and for WRF, I will register with IMWM.
