### ISSUE TITLE
source_id registration of ROAM-NBS

### ISSUE THREAD

**Issue by vmaurerDWD** [WCRP-CORDEX/cordex-cmip6-cv#186]
### label

ROAM-NBS

### label_extended

Regional coupled ocean-atmosphere model based on icon-2024.07 and NEMO4.2.0 for the North and Baltic Sea

### source_id

ROAM-NBS

### source_type

AORCM

### release_year

2024

### activity_participation

DD

### institution_id

DWD-BSH

### further_info_url

https://egusphere.copernicus.org/preprints/2024/egusphere-2024-923/

### What license do you choose?

CC BY 4.0

**Comment by vmaurerDWD** [comment]
This issue is linked to #180 - if it is required to have an institution ID like DWD-BSH to illustrate our partnership, then we would adapt #180 accordingly. However, if possible, I would like to stick to the two-institutions version. The inclusion of CLMcom-DWD should make it clearer that the atmospheric part of the coupled model ROAM-NBS is similar to the version used by CLMcom-DWD.

**Comment by jesusff** [comment]
Thank you for the clarifications, Vera. It is not required to register as a partnership, but each approach has a different meaning. To put it in practical terms, this depends on how the output files from your model simulations will be named and shared through the ESGF. From what I understand, this is a cooperation between the BSH and DWD to build a coupled model and use it to perform some CORDEX-compliant simulations. This cooperation could be reflected in the CV by defining a partnership BSH-DWD (or in the order you prefer) and simulations could be stored in a hierarchy such as:
```
/CORDEX/CMIP6/DD/EUR-12/BSH-DWD/MPI-ESM1-2-HR/historical/r1i1p1f1/ROAM-NBS/v1-r1/...
/CORDEX/CMIP6/DD/EUR-12/BSH-DWD/EC-Earth3-Veg/historical/r1i1p1f1/ROAM-NBS/v1-r1/...
```
Another possibility is that the cooperation is just that the coupled model already exists and both institutions have the ability and right to use it and you split (e.g.) by GCM the effort to contribute to CORDEX. This is what happens in the CLM community, for instance. Then, your data will ultimately be stored under, e.g.:
```
/CORDEX/CMIP6/DD/EUR-12/DWD/MPI-ESM1-2-HR/historical/r1i1p1f1/ROAM-NBS/v1-r1/...
/CORDEX/CMIP6/DD/EUR-12/BSH/EC-Earth3-Veg/historical/r1i1p1f1/ROAM-NBS/v1-r1/...
```
This registration process is a practical matter of having a controlled vocabulary collecting all values that will be allowed in ESGF for the `institution_id` of the CORDEX DRS (i.e. file and directory names). It is not about institutional visibility, although it could have some implications, of course.

In your case, this is further complicated by the additional presence of CLMcom in your naming, which depending of whether BSH is also part of CLMcom or not, might have different solutions. But we better discuss this in #180 when we clarify which of the options above (or another one) better reflect your situation.

Regarding the model registration. This looks fine to me, except that the `further_info_url` must be a single value and ideally point to further details of the coupled system you are using, rather to individual components. Is there any public resource (paper, report, ...) that could be linked? Otherwise, as a last resort you could describe here a bit the details of the model and especially how it differs from other coupled models using the same components. This issue will remain public and interested people will find it when searching for your model name in this CV. The `further_info_url` can always be updated when a better resource becomes available.

**Comment by vmaurerDWD** [comment]
Thank you for the clarification. We would opt then for the `institution_id` `DWD-BSH` . 

Concerning `further_info_url` , I can provide a pre-print of an article by Hagemann et al. The article describes the individual components of the regional coupled models, the coupling and the general performance.
I will provide the published version as soon as it is available. 

However, all of these components described in the article (apart from the runoff model HD) have later versions in the `ROAM-NBS` setup. 
For example, icon-2024.07 is the same code as used for the UDAG simulations (`source_id`  `ICON-CLM-202407-1-1`), apart from the OASIS interfaces that we cannot merge back into the official version. Also the setup is similar, apart from one namelist switch in the turbulence part mitigating a slight wintertime cold bias which would otherwise be increased in the coupled version. We're also preparing a publication describing all the details of `ROAM-NBS` (also including the background of the `DWD-BSH` partnership), but it will still take some time.

**Comment by jesusff** [comment]
That is great, thank you. With the preprint you linked and your further explanations above, I think is quite clear now. I'd say we can register. Would you like to have 2024 as the release year?

**Comment by jesusff** [comment]
/register

OK, this seems complete now. Thanks!
