### ISSUE TITLE
source_id registration of COSMO6-0-1-URB

### ISSUE THREAD

**Issue by marioRaffa** [WCRP-CORDEX/cordex-cmip6-cv#216]
### label

CCLM6-0-1-URB

### label_extended

COSMO model in climate mode (COSMO-CLM), Version 6.0 clm 1 with Urban Parametrization

### source_id

CCLM6-0-1-URB

### source_type

ARCM

### release_year

2021

### activity_participation

DD

### institution_id

CLMcom-CMCC

### further_info_url

https://www.clm-community.eu/COSMO-CLM/Overview

### What license do you choose?

CC BY 4.0

**Comment by jesusff** [comment]
Thank you, Mario. This is the first attempt to register the COSMO-CLM, at least as a standalone model. It is part of other coupled systems which referred to it in different ways (COSMO-CLM #204, COSMO #195). In CORDEX-CMIP5, it was registered with other names, which included the version (CCLM4-8-17, CCLM5-0-6). I'd just like to make sure that the name registered will be consistent with the upcoming ones from the CLM community. I especially miss a version number, as previous versions of this model have already been used in CORDEX.

@csteger, could you clarify whether there is an agreed naming pattern for COSMO-CLM in CORDEX-CMIP6? Otherwise, we could wait to have a consistent naming. No problem with temporary names in the simulation status (https://github.com/WCRP-CORDEX/simulation-status/pull/25), but changing registered `source_id`s can be confusing. 

Regarding the suffix (URB), it cannot be separated with underscores in the `source_id` as underscores are used to separate the different DRS elements in the filenames. You could use a dash instead.

Also, the `further_info_url` points to a list of versions and, when selecting [version 6.00](https://www.cosmo-model.org/content/model/cosmo/releaseNotes/cosmo_6.00.htm), it states that this version is the same as 5.14, and that version 6.00 itself was released in 2021. Since your `release_year` is 2024, I guess that your URB version is based on COSMO v6.00, but has some other modifications. Could you clarify?

**Comment by marioRaffa** [comment]
Thanks Jesus. 
Internally at the CLM-Community we have already received by @csteger (Christian Steger) the "naming-convention CORDEX document" for CMIP6 generation, related to COSMO and ICON. 
So, following this document, these are the corrections needed to be applied to our previous request:

label
CCLM-6-0-1-URB

label_extended
COSMO model in climate mode (COSMO-CLM), Version 6.0 clm 1 with Urban Parametrization

source_id
CCLM-6-0-1-URB

source_type
ARCM

release_year
2021

activity_participation
DD

institution_id
CLMcom-CMCC

further_info_url
https://www.clm-community.eu/COSMO-CLM/Overview 

What license do you choose?
CC BY 4.0

Is it enough this comment to register the source id or we should open a new issue with the corrections?
Thanks

**Comment by jesusff** [comment]
Perfect, thank you. No need to open a new issue. I changed your original post accordingly, please, check.

Note that there is now a dash between CCLM and the version (CCLM-6-0-1), while in CMIP5 it was all in a row (CCLM5-0-6). No problem at all, just to make sure this is intended. Thanks!

The `further_info_url` is quite generic, but this is OK for the moment. If in the future there's a publication or document describing this specific version, feel free to update it by reopening this issue or creating a new one.

**Comment by csteger** [comment]
Sorry for the delay. The standalone model should use the source_id CCLM6-0-1. Versions with other components included can than extend that (like CCLM6-0-1-URB) or use another shourt cut if the name would get too long otherwise (like Ha and Vera are doing for the coupled versions).

**Comment by jesusff** [comment]
Sorry, no dash, then, between the CCLM and the 6? Shall we keep the label the same as the source_id? One variant could be:
```python
source_id = "CCLM6-0-1-URB"
label = "CCLM v6.0 clm 1 URB"
```

**Comment by jesusff** [comment]
/register

OK, this was adapted to no dash. Also following #239
