### ISSUE TITLE
institution_id registration of Utrecht University

### ISSUE THREAD

**Issue by berg0138** [WCRP-CORDEX/cordex-cmip6-cv#222]
### institution_id

UU-IMAU

### institution

Utrecht University, Institute for Marine and Atmospheric Research Utrecht (IMAU), Utrecht, The Netherlands

**Comment by berg0138** [comment]
I wasn't 100% sure on the desired way to include our institute name (=IMAU) into the institute ID. Utrecht University is big.

**Comment by jesusff** [comment]
Thank you. The naming is up to you. Just to clarify: IMAU is part of UU, right? this a not a collaboration between two institutions (otherwise, there are other ways to represent that). If this is the case, maybe the institute could go first, to read from the most particular to the more general, up to the country. But this is totally up to you. E.g. you can use the affiliation you typically use in publications.

I assume this is related to https://github.com/WCRP-CORDEX/simulation-status/issues/36 so, when you decide on the final naming, I'll update the institution id there.

**Comment by berg0138** [comment]
IMAU is indeed a part of the UU. We normally use UU/IMAU, but I presumed this "/" is not allowed. Therefore, I took UU-IMAU.
Yes, this issue relates to https://github.com/WCRP-CORDEX/simulation-status/issues/36. I'll also create a new issue to introduce our model (version).

**Comment by jesusff** [comment]
/register

OK, looks fine, then.
