### ISSUE TITLE
source_id registration of RACMO24P

### ISSUE THREAD

**Issue by berg0138** [WCRP-CORDEX/cordex-cmip6-cv#223]
### label

RACMO24P

### label_extended

The KNMI and UU/IMAU Regional Climate Model RACMO, version 24P, based on IFS cy47r1 physics and with detailed parameterizations of glaciated surfaces

### source_id

RACMO24P

### source_type

ARCM

### release_year

2024

### activity_participation

DD

### institution_id

UU-IMAU

### further_info_url

https://tc.copernicus.org/articles/18/4065/2024/

### What license do you choose?

CC BY 4.0

**Comment by jesusff** [comment]
Thank you for the input. I see you use the same `source_id` and `label`. The latter can be used to have a less restricted model name such as RACMO v2.4 P

In the `label_extended`, you also refer to version 24P, but in the reference you provide it is referred to as v2.4p1. In this label, you can mention the exact name. This label is intended for tables with model listings. In this sense, your second sentence is a bit too elaborated. Would something like this work for you?:

> The KNMI and UU/IMAU Regional Climate Model RACMO, version 24P, based on IFS cy47r1 physics and detailed parameterizations of glaciated surfaces.

I CC also @erikvanmeijgaard, as I see that for RACMO2.3 (#174) he also registered 23 in all labels, instead of 2.3 (or RACMO2v3, as in the documentation linked there). If you both agree, there's no problem in keeping this 23/24 notation. Just to let you know that the labels are more flexible than the source_id.

**Comment by berg0138** [comment]
Hi Jesus, 
Thanks for your comments. Internally, we call our version version 2.4p. So, with dot and lower case p. However, for consistency with the KNMI version of RACMO, I would opt for 24P. 
Concerning the label_extended, your suggestion is good, I only added a "with" at the end, so that is becomes:

The KNMI and UU/IMAU Regional Climate Model RACMO, version 24P, based on IFS cy47r1 physics and _with_ detailed parameterizations of glaciated surfaces.

**Comment by jesusff** [comment]
/register

OK, thanks!
