### ISSUE TITLE
experiment_id or driving_experiment_id

### ISSUE THREAD

**Issue by gnikulin** [WCRP-CORDEX/cordex-cmip6-cv#23]
There are 3 CMIP6-related elements with `driving`: `driving_institute_id`, `driving_source_id` and `driving_experiment_id`. The first 2 “driving”- elements are used to distinguish from the CMIP6 `institute_id` and  `source_id` (new values in CORDEX) while `driving_experiment_id` has the same values in both CMIP6 and CORDEX. Should we simply use `experiment_id` instead of `driving_experiment_id` ? The respective CV is actually named - CORDEX-CMIP6_experiment_id.json .

**Comment by jesusff** [comment]
I would keep the "driving" here, and rename the file to `CORDEX-CMIP6_driving_experiment_id.json` to make clear that this experiment_id refers to the driving data. In CORDEX, only a very small subset of the [CMIP6 experiment_id](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json)s are allowed. Unfortunately, for the moment, the only example we have for the [driving_experiment_id](https://github.com/WCRP-CORDEX/cordex-cmip6-cv/blob/e3ddca5/CORDEX-CMIP6_experiment_id.json) refers to the ERA5-driven simulations, which is not a very good example. We should try to improve this file. I would propose using a subset of the CMIP6 experiment_id and try to fit there evaluation experiment, not existing in CMIP6. E.g: something like:
```json
        "historical":{
            "activity_id":[
                "DD",
                "ESD"
            ],
            "description":"CMIP6 historical",
            "end_year":"2014",
            "experiment":"all-forcing simulation of the recent past",
            "experiment_id":"historical",
            "parent_experiment_id":[
            ],
            "start_year":"1950",
        },
        "ssp370":{
            "activity_id":[
                "DD",
                "ESD"
            ],
            "description":"Future scenario with high radiative forcing by the end of century. Reaches about 7.0 W/m2 by 2100; fills gap in RCP forcing pathways between 6.0 and 8.5 W/m2. Concentration-driven",
            "end_year":"2100",
            "experiment":"gap-filling scenario reaching 7.0 based on SSP3",
            "experiment_id":"ssp370",
            "parent_experiment_id":[
                "historical"
            ],
            "start_year":"2015",
           },
```
And then we can make up one based on these for the evaluation run:
```json
        "evaluation":{
            "activity_id":[
                "DD",
                "ESD"
            ],
            "description":"CMIP6 historical",
            "end_year":"2021",
            "experiment":"ERA5 reanalysis-driven evaluation simulation of the recent past",
            "experiment_id":"evaluation",
            "parent_experiment_id":[
            ],
            "start_year":"1979",
        },
```
If we keep the years, we should think if we show the recommended periods or the minimum to be CORDEX-CMIP6 compliant according to the [CORDEX-CMIP6 experiment design for DD](https://cordex.org/wp-content/uploads/2021/05/CORDEX-CMIP6_exp_design_RCM.pdf).

Proper CORDEX-CMIP6 `experiment_id`s would be another matter for discussion, maybe in the context of #20 , since we need to clarify the activity / experiment wording within CORDEX. E.g. with the latest discussions here, the above document would be describing the _CORDEX-CMIP6 design of the **activity** DD in continental domains_. 

There are also some CORDEX experiments within the activity [here](https://github.com/WCRP-CORDEX/simulation-status/blob/main/CORDEX_CMIP6_experiments.yaml) (and rendered [here](https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status_by_experiment.html#EUR-11)), although these have not yet been discussed. They are though of as experiments free to be designed by the regional CORDEX communities to explore particular uncertainties/aspects.

**Comment by gnikulin** [comment]
OK, seems it's better to use conventional `driving_experiment_id` to represent the CMIP6 `experiment_id` and leave space for CORDEX-defined experiments of different kind. Here, we need to include all ScenarioMIP Tier 1 experiments (ssp126, 245, 370, 585) and perhaps ssp119 from Tier 2.

`experiment_id` should be changed to `driving_experiment_id` in the above examples ?

Regarding `start_year`and `end_year`, I'm not sure if we really need them here. The CORDEX-CMIP6 experiment design provide "minimum" recommendations e.g. for the ERA5-driven experiment "the entire 1979-2020 period, or a longer period depending on the availability of the ERA5 forcing" or for the historical one  "the CORDEX historical simulations have to cover at least 1960-2014 or preferably the entire 1950-2014 period". Some groups can downscale even the entire historical period from 1850. 

We may keep `start_year`and `end_year` for all CMIP6 experiments as they are while for the evaluation experiment `start_year=""`and `end_year=""`. Some groups may be interested in downscaling of the ERA5 back extension from 1950 ?

**Comment by jesusff** [comment]
I made an example dropping the years and including all ˋdriving_experiment_idˋs. For simplicity, I dropped also the parent_experiment_id. We could even further simplify this CV by reducing it to a simple list of ˋdriving_experiment_idˋs and their description, as in many of the other json files. Full details are already available from the CMIP6 CV:

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/a66ba120a5329f58e98de09d4dc06c1a086a7002/CMIP6_experiment_id.json#L8555-L8584

**Comment by larsbuntemeyer** [comment]
Ok, i got that, thanks Chus! I did something similar with the driving_source_id. Right now, it’s simply derived from the source_id in CMIP6 using a script...

My simple question now is, should we keep `experiment_id` as a [required attribute]() or only `driving_experiment_id`?

**Comment by larsbuntemeyer** [comment]
Should we rename that to `CORDEX-CMIP6_driving_experiment_id.json`? I'll then add it to the actions workflow which will update the actual CORDEX-CMIP6_CV.json.

**Comment by jesusff** [comment]
Yes, I forgot to rename it. I was also thinking to simply set this CV as:
```json
{
    "driving_experiment_id": {
        "evaluation": "ERA5 reanalysis-driven evaluation simulation of the recent past",
        "historical": "CMIP6 historical. All-forcing simulation of the recent past",
        "ssp119": "Future scenario with low radiative forcing throughout reaching about 1.9 W/m2 in 2100 based on SSP1. Concentration-driven",
        "ssp126": "Future scenario with low radiative forcing by the end of century. Following approximately RCP2.6 global forcing pathway but with new forcing based on SSP1. Concentration-driven",
        "ssp245": "Future scenario with medium radiative forcing by the end of century. Following approximately RCP4.5 global forcing pathway but with new forcing based on SSP2. Concentration-driven",
        "ssp370": "Future scenario with high radiative forcing by the end of century. Reaches about 7.0 W/m2 by 2100; fills gap in RCP forcing pathways between 6.0 and 8.5 W/m2. Concentration-driven",
        "ssp585": "Future scenario with high radiative forcing by the end of century. Following approximately RCP8.5 global forcing pathway but with new forcing based on SSP5. Concentration-driven"
    }
}
```
I'm not sure any of the other info is necessary. We just need to define which are the valid values to use for `driving_experiment_id` and the corresponding `driving_experiment`, right?

**Comment by gnikulin** [comment]
Yes, we only need `driving_experiment_id` and the corresponding `driving_experiment`. It's the `description` element from CMIP6_experiment_id.json  in the above example, should be `experimen`e.g. `update of RCP2.6 based on SSP1`for ssp126.

**Comment by jesusff** [comment]
You are right. It would look like this then
https://github.com/WCRP-CORDEX/cordex-cmip6-cv/blob/8a8a35172f96287daef7696227615543f73016fa/CORDEX-CMIP6_driving_experiment_id.json#L1-L11

@larsbuntemeyer do you prefer it to be automtically generated from the CMIP6 CV? The `evaluation` one needs to be created manually anyway (@gnikulin please check the current driving_experiment for evaluation).

**Comment by gnikulin** [comment]
the current `driving_experiment` for evaluation is fine

**Comment by larsbuntemeyer** [comment]
Yes, i think this should be fine. I'll update the CV_table soon and that should trigger some tests. There could be some issues with the cmor3 library if we mess to much with id variables from CMIP6 (there is some hardcoded stuff sometimes). But the tests should cover this...
